/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_unomic_hellondk4_NDKTest */

#ifndef _Included_com_example_unomic_hellondk4_NDKTest
#define _Included_com_example_unomic_hellondk4_NDKTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_unomic_hellondk4_NDKTest
 * Method:    ndkTestMethod
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_unomic_hellondk4_NDKTest_ndkTestMethod
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_unomic_hellondk4_NDKTest
 * Method:    getHelloNDKString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_unomic_hellondk4_NDKTest_getHelloNDKString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
